server:
  port: 9092
  servlet:
    context-path: /market-orders-ws

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/orders
    username: java
    password: java
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

integrations:
  cart-service:
    url: http://localhost:9091/market-carts-ws/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 2000

#
#logging:
#  level:
#    root: error
#    gb.spring.emarket: warn
#  file:
#    name: eshop-log.log
#  logback:
#    rollingpolicy:
#      file-name-pattern: eshop-log-%d{yyyy-MM-dd}.%i.log
#      max-file-size: 100KB
#      total-size-cap: 1MB
#      max-history: 14
#      clean-history-on-start: true
#
